### ISSUE TITLE
overlay is enabled despite setting MENU = false

### ISSUE THREAD

**Issue by vaaski** [AStupidRat/RatPoison#10]
basically what it says in the title, on latest 1.2.5

![image](https://user-images.githubusercontent.com/17879327/57081502-21b7ed00-6cf5-11e9-9b54-d4968b1cb609.png)

**Comment by AStupidRat** [comment]
Create a cfg, copy+paste the contents to a pastebin and link it here

**Comment by AStupidRat** [comment]
Latest push should fix it, lmk if it does or not.

**Comment by vaaski** [comment]
yes, that fixed it.
thanks
