### ISSUE TITLE
dangerzone aim is not working

### ISSUE THREAD

**Issue by vaaski** [AStupidRat/RatPoison#13]
aim doesn't seem to work with dangerzone on the new sirocco.
even with TEAMMATES_ARE_ENEMIES enabled. they aren't highlighted either.

on 3227dce043c569ce556ce6eb9d2e69fc7d2de982
[config](https://pastebin.com/h937C2qv)

**Comment by AStupidRat** [comment]
Latest update should fix aim not working, there isn't a visibility check in dz, so force aim key/aim key can track through walls and shit, and bone trigger will disable in dz.
