### ISSUE TITLE
Warning on every build

### ISSUE THREAD

**Issue by gitanon69** [AStupidRat/RatPoison#2]
The hack works fine, but every time i rebuild it (for new updates) i get the following warning:
`
C:\Users\Username\RatPoison-master\src\main\kotlin\rat\poison\scripts\esp\ChamsESP.kt: (59, 9) 'when' expression on enum is recommended to be exhaustive, add 'NULL', 'CAK47', 'CBaseAnimating', 'CBaseAnimatingOverlay', CBaseAttributableItem', 'CBaseButton', ... branches or 'else' branch instead`

**Comment by gitanon69** [comment]
Also, how do I make my settings consistent throughout updates? It either deletes my config or the new options/settings never turn up, unless i delete the whole thing and rebuild from scratch.

**Comment by AStupidRat** [comment]
I've known about the warning, it doesn't break anything so I haven't really cared to fix it yet. Also you can just copy your settings over from the old version to the new one and it will work fine if I haven't renamed/added any settings.
