### ISSUE TITLE
Aimbot sometimes suddenly aims to the right

### ISSUE THREAD

**Issue by TheTreeThatGrows** [AStupidRat/RatPoison#21]
As the title says, when using the aimbot it sometimes suddenly aims to the right by like 50-90 degree, making it look very suspicious.

**Comment by TheTreeThatGrows** [comment]
Been testing for a couple of hours now and the issues seems to have been fixed :). However, when using RCS, sometimes after spraying with a rifle or smg, the crosshair suddenly moves down. This only happens when RCS is turned on.

**Comment by AStupidRat** [comment]
RCS had an issue where it would flick straight down to your feet but that should have been fixed, is this the same issue you're having?

**Comment by TheTreeThatGrows** [comment]
Yes, it keeps happening more often now compared to the previous versions

**Comment by AStupidRat** [comment]
Are you using the default settings for rcs or no? If not what smoothing and is return aim enabled or disabled?

**Comment by TheTreeThatGrows** [comment]
I'm using the default settings for RCS with return aim disabled. Enabling return aim seems to fix it but when I look around during the return aim duration, it keeps shaking the screen as if its forced by the return aim.

**Comment by AStupidRat** [comment]
Happens to me when im tapping 2+ shots at a time, I don't have a fix atm but will comment here when I do

**Comment by AStupidRat** [comment]
@TheTreeThatGrows Latest hotfix should fix it, lmk if it does

**Comment by TheTreeThatGrows** [comment]
@AStupidRat Been testing for a couple of hours now and haven't encountered any flick relating bug, including the RCS bug. Everything seems to be working perfectly now :)
