### ISSUE TITLE
Menu is broken...

### ISSUE THREAD

**Issue by Evilhelder** [AStupidRat/RatPoison#22]
The menu is off screen so I can not play in the other sections.... I tried to change the menu resolution but it does not change... 

![Screenshot_1115](https://user-images.githubusercontent.com/33970481/57394447-f2ddc300-719b-11e9-8365-14c12bb39108.png)

**Comment by astupidhat** [comment]
That is an older version, download the latest

**Comment by AStupidRat** [comment]
That's an older version, download the latest from here.

**Comment by Evilhelder** [comment]
> 
> 
> That's an older version, download the latest from here.

its work thanks, so much...
