### ISSUE TITLE
Menu Blinking

### ISSUE THREAD

**Issue by Usernameistakensad** [AStupidRat/RatPoison#24]
So when i open the menu after like 3 seconds it closes down and i have to tab out and back into the game for it to show up again for 3 seconds. Dont know if its any thing i messed with in the files but i tried rebuilding it andit still glitches. Is it a known issue or just me?

**Comment by AStupidRat** [comment]
Are you using windowed or borderless fullscreen?

**Comment by Usernameistakensad** [comment]
Hey im using Borderless fullscreen currently.

**Comment by AStupidRat** [comment]
If you could pastebin a cfg (if possible) or upload your settings files (or folder) here, it probably wont help but having the same settings would help me limit any problems. First I've heard of the issue, and make sure you're using the latest version.

**Comment by Usernameistakensad** [comment]
> If you could pastebin a cfg (if possible) or upload your settings files (or folder) here, it probably wont help but having the same settings would help me limit any problems. First I've heard of the issue, and make sure you're using the latest version.

Ill do it as soon as im home.

**Comment by Usernameistakensad** [comment]
But i was on the 1.3 build

**Comment by Usernameistakensad** [comment]
http://www.mediafire.com/folder/dd682arxhcp3n/settings Is the settings im using its blinking with it.

**Comment by AStupidRat** [comment]
Your settings are missing GunAimOverride.kts and IndicatorEsp.kts, so I'm assuming you're on an older version, so unless the problem persists in the current version available here I can't help, though with your settings on the latest version (with the default GunAimOverride and IndicatorEsp) it is working fine for me.

**Comment by Usernameistakensad** [comment]
> Your settings are missing GunAimOverride.kts and IndicatorEsp.kts, so I'm assuming you're on an older version, so unless the problem persists in the current version available here I can't help, though with your settings on the latest version (with the default GunAimOverride and IndicatorEsp) it is working fine for me.
> 
> Also since the menu shows up at all I'm assuming you're not using fullscreen, but just so you know the menu only works (normally) on borderless or windowed.

Okey im downloading the newest installation of ratposion rn.

**Comment by AStupidRat** [comment]
Is the problem that the overlay disappears after a few seconds? Or just the F1 Menu? The crosshair in the middle of the screen is the recoil crosshair from the overlay.

**Comment by Usernameistakensad** [comment]
> Is the problem that the overlay disappears after a few seconds? Or just the F1 Menu? The crosshair in the middle of the screen is the recoil crosshair from the overlay.

The Cheat menu disepears after a few seconds than i gotta press f1 twice or Alt tab for it to get fixed for 3 seconds more.

**Comment by AStupidRat** [comment]
So to be clear, the menu that pops up disappears after a few seconds, but everything else drawn on the overlay is fine (such as box esp/recoil crosshair/indicators)?

**Comment by Usernameistakensad** [comment]
Yea @AStupidRat The in game ESP and glow all like that shows the bomb time and the crosshair dose its only with the cheat menu.

**Comment by AStupidRat** [comment]
Change the menu key to something like F (70) and see if the issue persists

**Comment by Usernameistakensad** [comment]
Yep it still happend when i changed the button to F.

**Comment by Usernameistakensad** [comment]
If you want to i could screenshare on discord if u want?

**Comment by AStupidRat** [comment]
Let me know if the latest update fixes it

**Comment by Usernameistakensad** [comment]
> Let me know if the latest update fixes it

Just installed and tried the latest one that was updated a few mins ago and it did not fix it :/

**Comment by Usernameistakensad** [comment]
@AStupidRat Hey Just changed my mode to Windowed and its working so i think its some time to do with Noborderwindowed. https://gyazo.com/04a9056057baae83e359eb6e55a1a915

**Comment by AStupidRat** [comment]
I use borderless and it works fine for me, Ill probably be trying fixes over updates, but for now I don't have any fix.

**Comment by Usernameistakensad** [comment]
> I use borderless and it works fine for me, Ill probably be trying fixes over updates, but for now I don't have any fix.

Ok np ill just change settings in windowed and change it to noborder when im done.

**Comment by AStupidRat** [comment]
Drop your discord just in case I need it too

**Comment by Usernameistakensad** [comment]
MrSquid#8277
