### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by solohin300** [AStupidRat/RatPoison#25]
when the cheat is turned on, nothing happens, the Rat Poison UI application is turned on, which does not open. I tried out in all modes from full-screen to window without frame. In the game itself, the menu on the F1 key works, the menu opens, but everything around the menu is black
[https://imgur.com/a/AeTJu8x](url)

**Comment by AStupidRat** [comment]
Im only supporting windows 10 atm, and that doesn't look like it.

**Comment by Usernameistakensad** [comment]
> Im only supporting windows 10 atm, and that doesn't look like it.

Hey im running Windows 10 Latest build if you got discord i could screenshare it. my tag is MrSquid#8277
