### ISSUE TITLE
Discord username is wrong

### ISSUE THREAD

**Issue by archpc** [AStupidRat/RatPoison#3]
What happens: Overlay shows Discord username as Stupid Rat#9999

Why this is an issue: Discord username is incorrect, "Hm, didnt. work. Double check that the capitalization, spelling, any spaces, and numbers are correct."

What should happen: The correct username and/or Discord server should appear in overlay.

**Comment by AStupidRat** [comment]
Had to change my tag for a few days, should be fine now
