### ISSUE TITLE
F1 Menu Not opening~

### ISSUE THREAD

**Issue by codyxd** [AStupidRat/RatPoison#30]
This is the error i'm getting now. The previous build was better and showed me no errors.
![err0r](https://user-images.githubusercontent.com/47775604/57510875-6d861a00-7325-11e9-910e-6c36401bf526.png)

**Comment by AStupidRat** [comment]
@codyxd I forgot to include the gunaimoverride.kts file when updating, the latest hotfix should include it and fix the error. Please close this issue if it does
