### ISSUE TITLE
Overlay is not opening 

### ISSUE THREAD

**Issue by Pakte** [AStupidRat/RatPoison#31]
it says Initializing overlay but does not open when pressing f1 it just minimize

**Comment by AStupidRat** [comment]
If 'it just minimize' means it minimizes CSGO, id assume csgo is fullscreen, overlay only works with borderless or windowed cs.

**Comment by Pakte** [comment]
> 
> 
> If 'it just minimize' means it minimizes CSGO, id assume csgo is fullscreen, overlay only works with borderless or windowed cs.

**Comment by Pakte** [comment]
> 
> 
> If 'it just minimize' means it minimizes CSGO, id assume csgo is fullscreen, overlay only works with borderless or windowed cs.

Is this vac detected or can it be detected in future ???

**Comment by AStupidRat** [comment]
Currently? No, and anything CAN be detected.

**Comment by Pakte** [comment]
It says not detected for 2 years and 6 months so its never been detected
for real?

**Comment by AStupidRat** [comment]
Not that I know of

**Comment by Pakte** [comment]
Thank you for everything
