### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LauraSavall** [AStupidRat/RatPoison#34]
Is it possible to add or to give me 
`val dwForceRight by clientDLL(2)`
and
`val dwForceLeft by clientDLL(2)`

Thanks

**Comment by 10urshin** [comment]
https://github.com/frk1/hazedumper/blob/master/config.json#L196

**Comment by LauraSavall** [comment]
Thanks !

**Comment by LauraSavall** [comment]
I tried my thing.. but I guess I've more to learn before doing this xD
` private var isLeft = false
private var isJumping = false

fun bunnyHop() = onGround {
    if (curSettings["ENABLE_BUNNY_HOP"]!!.strToBool() && !cursorEnable && keyPressed(BUNNY_HOP_KEY)) {
      CSGO.clientDLL[ClientOffsets.dwForceJump] = 6//if (jump) 5 else 4
      if (isLeft) {
        CSGO.clientDLL[ClientOffsets.dwForceLeft] = 4.toByte() //Left release
        CSGO.clientDLL[ClientOffsets.dwForceRight] = 5.toByte() //Right press
      } else {
        CSGO.clientDLL[ClientOffsets.dwForceRight] = 4.toByte() //Right release
        CSGO.clientDLL[ClientOffsets.dwForceLeft] = 5.toByte() //Left press
      }
      isLeft = !isLeft
      isJumping = true
    }
    if (curSettings["ENABLE_BUNNY_HOP"]!!.strToBool() && keyReleased(BUNNY_HOP_KEY) && !isJumping) {
      if (isLeft) {
        CSGO.clientDLL[ClientOffsets.dwForceLeft] = 4.toByte() //Left release
      } else {
        CSGO.clientDLL[ClientOffsets.dwForceRight] = 4.toByte() //Right release
      }
      isLeft = false
      isJumping = false
    }
} `

**Comment by 10urshin** [comment]
use 6 and you are toggling isLeft too fast.
