### ISSUE TITLE
Overlay UI issue

### ISSUE THREAD

**Issue by LauraSavall** [AStupidRat/RatPoison#36]
I have CSGO on Borderless Fullscreen, but Overlay is still in background which is not cool...

Tested with Windowed, same result... so, I can't use bomb timer neither indicator etc

**Comment by AStupidRat** [comment]
Not much info I can work with, working fine for me.

**Comment by LauraSavall** [comment]
I see...
Maybe my launch setting of CSGO ?
-novid -high +exec autoexec -threads 8 -freq 60 -refresh 60 +fps_max 240 +mat_queue_mode 2 -nojoy -no-browser

But yes... I don't know... Charlatano worked fine, yours too, only the RatPoison UI not in frontend

**Comment by LauraSavall** [comment]
nb :
It's not launch settings :/

No problem, I wrote my own bomb timer in CMD console and bind numpad cf screen

same for defusing ^^

![image](https://user-images.githubusercontent.com/45919164/57745676-6321a280-76ce-11e9-8795-af64e07b434e.png)
