### ISSUE TITLE
CANNOT INSTALL. SOMEONE PLEASE UPLOAD A COMPILED VERSION TO GOOGLE DRIVE AND GIVE IT TO ME THANKS 

### ISSUE THREAD

**Issue by phooooon** [AStupidRat/RatPoison#4]
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_211' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
Press any key to continue . . .

everything i need is installed

**Comment by archpc** [comment]
Install this exact JDK, https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-windows-x64.exe (you need to make an account, Idk why) then reboot your PC and try building again. Let me know how it goes.

**Comment by AStupidRat** [comment]
Need to have jdk 8 installed, not a later version, thought I changed that in the readme but apparently not. https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by quynhchi60** [comment]
If you used window 10, the following may work
Right click on file jdk-8u211-windows-x64.exe that you just download
Then select Trouble shoot compatibility
Try recommended setting
Test the program
then follow screen instructions to install
After that execute java -version to check you should see the following
java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by phooooon** [comment]
@quynhchi60 fixed long ago
