### ISSUE TITLE
bypass anti cheats

### ISSUE THREAD

**Issue by amanya021** [AStupidRat/RatPoison#44]
as we see this cheat can easy hide itself from VAC.
my question is "can this cheat stay hidden from league anti cheats like Easy Anti Cheat(E sports anti cheat)?.can we use it in leagues without getting banned?

**Comment by 10urshin** [comment]
You can only last a few weeks

**Comment by amanya021** [comment]
it means it detects but wont ban and will ban you after weeks pass?

**Comment by amanya021** [comment]
or it detects from your play style?
