### ISSUE TITLE
Ratpoison 1.3.2 eats lots of FPS

### ISSUE THREAD

**Issue by csirketorta** [AStupidRat/RatPoison#45]
Today i have downloaded 1.3.2 from github (my previous install was 1.3(.0)) and it is eating lots of processor time, which is not good, because ratpoison is used to be lightweight. 
My settings are: https://anonfile.com/e3Z7w6san7/settings_zip

**Comment by Loobo1** [comment]
I don't know it this is true but some people told me it have an inbuilt bitcoin miner that mines to the "owner" of the cheat

**Comment by AStupidRat** [comment]
@Loobo1 Lmao find it in the source code and get back to me.

@csirketorta Use the menu to set your settings in Aimbots or some test map then try using it without the menu, you won't be able to use things like box esp, indicator esp, and bomb timer but it should run smoother for you.
