### ISSUE TITLE
Need help in changing signature

### ISSUE THREAD

**Issue by furioushell98** [AStupidRat/RatPoison#48]
Honestly i don't understsnd a lot in cheating but I was able to build the cheat and it worked fine. But not changing anything to the source will make me have the same signature as many other users, and that's worrying since i cheat on my main account and i don't want to get vacced. So i thought maybe you'd be willing to provide me with a guide/some tips to have a unique signature, and how much time i can use it before getting a new signature and ty.

**Comment by UrAvgCoder** [comment]
I don't if I am qualified for answering, but since its based on JVM(Java Virtual Machine), it uses ByteCodes to generate the file. Hence, I presume, every time you build you'll get a new signature?
