### ISSUE TITLE
Legit config for RatPoison

### ISSUE THREAD

**Issue by furioushell98** [AStupidRat/RatPoison#49]
I really tried hours to get legit settings  in the aimbot tab for pistols/rifles/snipers but it always looks suspicious when i try deathmatch, i'd really appreciate some help in configuring the aimbot tab (perfect aim fov/chance, strictness, Fov, aim speed) for legit hacking in prime, main account

**Comment by Dorfbewohner3000** [comment]
Why hack on main :D Dont hack at your main

**Comment by UrAvgCoder** [comment]
> I really tried hours to get legit settings in the aimbot tab for pistols/rifles/snipers but it always looks suspicious when i try deathmatch, i'd really appreciate some help in configuring the aimbot tab (perfect aim fov/chance, strictness, Fov, aim speed) for legit hacking in prime, main account

I don't know but, the shipped settings is actually pretty legit. If anyone has modified the defaults and have come up with a legit setting, please attach them here.

**Comment by furioushell98** [comment]
@Dorfbewohner3000 but the cheatbis undetected since 2 years and 6 months and it has a license that protects it from being detected, it should be safer than all famous paid cheats that keep getting detected every while.

@UrAvgCoder i tried the default aim settings, you basically every fight, you kill anyone within 2 or 3 seconds using rifle/pistol/awp, and if you're fighting two people that are close to each other your crosshair will snap to the other guy in a quick strange way instead of focusing on the first target, what i need if possible is some settings that i won't get called out / reported for it.

**Comment by UrAvgCoder** [comment]
@furioushell98 
I kinda managed to reduce the aimbot "shift" when fighting close people, though I only changed it for Pistols, Rifles and Sniper. You can use the same idea for the SMG section of the weapon group too. Play around with my settings and let me know how you feel.

Regarding the detection rate of the cheat, we know it's been UD for 2 years now, thats really impressive, but there's always a risk that is bound to take place when you use cheat of any sort, there will always be human faults which might make the cheat go detected. I would not recommend using the cheat on your main. Just a heads up.

> it has a license that protects it from being detected, it should be safer than all famous paid cheats that keep getting detected every while.
> 

Also, which license were you talking about?

[settings.zip](https://github.com/AStupidRat/RatPoison/files/3244815/settings.zip)

**Comment by furioushell98** [comment]
@UrAvgCoder thank you mate! I will try the config tonight and let you know how it went. Sorry for the bother and ty again.
About the license, check out this : 
https://www.google.com/amp/s/amp.reddit.com/r/VACsucks/comments/a3b4q4/please_ban_my_cheat_valve_do_it/
This was posted by Jire, the guy who created Charlatano(Ratpoison now) apparently Cheats licensed under "AGPL3" can't be detected. 
2 years and 6 months + this post is the reason why i had the courage to run the cheat on my main account, i wouldn't carelessly try a free public cheat on my main if it weren't for this. There's always a vac ban risk but i think it's a very small one for this cheat. Despite being public and free, it remained undetected even better than paid ones, it's amazing.

**Comment by UrAvgCoder** [comment]
> @UrAvgCoder thank you mate! I will try the config tonight and let you know how it went. Sorry for the bother and ty again.
> About the license, check out this :
> https://www.google.com/amp/s/amp.reddit.com/r/VACsucks/comments/a3b4q4/please_ban_my_cheat_valve_do_it/
> This was posted by Jire, the guy who created Charlatano(Ratpoison now). apparently Cheats that are licensed under "AGPL3" can't be detected.
> 2 years and 6 months of being undetected + this Reddit post is the reason why i had the courage to run the cheat on my main account, i wouldn't carelessly try a free public cheat on my main if it wasn't for this. There's always a vac ban risk but i think it's a very small one for this cheat. Despite being public and free, it remained undetected even better than paid ones, it's amazing.
> I'm currently leveling up an alt account so i can get into prime and stop using the cheat on main, so all good.

Glad to have you helped. Ya just read the post and damn, it's really good considering the coder himself has put the reddit post. Now that's some good shit haha.

**Comment by furioushell98** [comment]
@UrAvgCoder, i tried your settings, awp settings are perfect, i almost never miss but i still look legit, i just have to "not get every kill and die sometimes", pistols look legit as well, rifles are a bit obvious because of the RCS so i disabled that and i use Recoil crosshair instead to look more legit, but the aimbot tab settings are perfect, chams' config is nice as well. it's perfect, ty man.

**Comment by AStupidRat** [comment]
I typically use the default settings, have been fine using it the past few months.

**Comment by hetulshah** [comment]
whats the bind to access all these settings and config ingame?

**Comment by furioushell98** [comment]
@hetulshah default key should be F1 afaik. Been months since last time i tried RP.

**Comment by hetulshah** [comment]
@furioushell98 alr thanks. also does this work in faceit?

**Comment by furioushell98** [comment]
@hetulshah it should work on serverside Faceit, but not with the client.
when you just created your faceit account you can play few games without having to install their anti cheat client. that's called serverside Faceit and there you should be able to use Ratpoison. But then later they'll force you to install it in order to play after few reports-in game or matches. That's where you cannot use RP anymore.
