### ISSUE TITLE
Chams glow White on teammates and local player.

### ISSUE THREAD

**Issue by UrAvgCoder** [AStupidRat/RatPoison#51]
Basically the title. 
Even tho I have not selected the chams for teammates, it makes them white(kinda glowish white) and the local player too is in white glowsih chams.
I did not change any of my config, I just did a rebuild to get the default settings and tried turning on chams for only ENEMIES, and it still glows it for teammates and localplayer.
Any possible solution?

**Comment by AStupidRat** [comment]
Found an issue with it coloring teammates, latest hotfix should fix it. Local player being white/parts of enemies/teammates being white is due to shader detail being too high, lowering it should fix that.

**Comment by UrAvgCoder** [comment]
Thanks will look into that soon! Thanks for the hotfix tho!

**Comment by AStupidRat** [comment]
![csgo](https://i.gyazo.com/83cf25e91e70e3a369d1a446880a7acb.jpg "Chams")
Low shader detail fixes any white problems for me.

**Comment by UrAvgCoder** [comment]
I'll give a one more try with rebuilding ratpoison and will let you know.
