### ISSUE TITLE
Sometimes aimlock flies to the right

### ISSUE THREAD

**Issue by KenWa51** [AStupidRat/RatPoison#52]
no idea what causes it but default settings sometimes it flies over to the right.

**Comment by Usernameistakensad** [comment]
> no idea what causes it but default settings sometimes it flies over to the right.

Are you using the newest release if not please try to download it and try it out good luck!

**Comment by KenWa51** [comment]
Latest

**Comment by AStupidRat** [comment]
https://github.com/AStupidRat/RatPoison/issues/21 This has already been addressed, unless you can provide a way to accurately replicate the issue I can't do anything. I haven't had the issue myself and the people who had the problem haven't brought it back up.
