### ISSUE TITLE
Trigger bot not working

### ISSUE THREAD

**Issue by TheTreeThatGrows** [AStupidRat/RatPoison#53]
Trigger bot doesnt seem to work. I've binded the key to activate trigger bot to F, but it still wont activate after the aimbot locks on to an enemy

**Comment by AStupidRat** [comment]
https://i.gyazo.com/3809086a7c2f77e3cdf82ce5de719277.mp4 working fine here, video is with only using force aim key & bone trigger key, all the settings are default except the ones changed in the bone trigger tab.
