### ISSUE TITLE
the overlay is just a black screen

### ISSUE THREAD

**Issue by CoolAsRice** [AStupidRat/RatPoison#57]
Whenever I open the cheat, it's just a blackscreen. I'm using Windows 7 and my graphics drivers are up to date as well as Jdk and jre

**Comment by AStupidRat** [comment]
Windows 10 is the only supported version

**Comment by GIGIGIVEVEH** [comment]
> Windows 10 is the only supported version
im sorry ,but win10 still just a black screen .
my win10 version is 64-17763.
ps: waller works but covered by the black screen.
