### ISSUE TITLE
Sometimes when i use SMG's, it aims to the left mostly.

### ISSUE THREAD

**Issue by codyxd** [AStupidRat/RatPoison#59]
when i click for firing, the aim goes to the left

**Comment by AStupidRat** [comment]
Something similar was addressed before https://github.com/AStupidRat/RatPoison/issues/21 is this similar? Are you using default settings? Provide a cfg if not, and any way to replicate if possible.

**Comment by codyxd** [comment]
uh well, I've only set my force aim key to middle mouse button/ (4) 
The rest is default setting. Its just, I rush with my smg/any smg and when im shooting, it after the first few bullets, it starts aiming to the left

**Comment by 10urshin** [comment]
There was a bug at charla when you are too close to the enemy and enemy is your right, aim helper was taking the long way from left to aim. Probably someone forgot to normalize/clamp the angle somewhere. Don't know if it ever got fixed. Maybe the same issue ? It was only happening on one of the aim models tho. Don't remember which one either :)

**Comment by AStupidRat** [comment]
Using the fastest settings, looks like its aiming fine to me, might just look like its doing it incorrectly because its slower with normal settings to look legit. https://gyazo.com/16c663585ecda11b9097ad5981aeccad

**Comment by 10urshin** [comment]
> Provide any way to replicate if possible.

https://streamable.com/2mxs6

Walk around someone with force aim enabled. It will happen eventually.
