### ISSUE TITLE
Will fullscreen be supported in the future?

### ISSUE THREAD

**Issue by nitrogen69** [AStupidRat/RatPoison#6]
The header says everything, thanks in advance :)

**Comment by AStupidRat** [comment]
The use of the overlay when fullscreen will not be supported by me, though you can still use the cheat with the overlay disabled, if you want to do this I recommend using windowed/borderless in a workshop map to get all of your settings the way you want them and save those settings to default. Then set MENU = false in General.kts and that will disable the overlay and your settings should work just fine. Just a warning that I have done practically 0 testing with not using the overlay so it may not be stable.
