### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by suvajac99** [AStupidRat/RatPoison#63]
On win7 working just aim, wont work wallhack or bhop. Can you help me fix it or I must do win10?

**Comment by suvajac99** [comment]
Actually I had win10 and its worked perfect, then I had to instal win7, I just copy folder with same settings and it isn't work properly. Working just aim like I said, but WH and Bhop won't. Is it problem win7?

**Comment by AStupidRat** [comment]
Only windows 10 is supported
