### ISSUE TITLE
Triggerbot inconsistent?

### ISSUE THREAD

**Issue by phooooon** [AStupidRat/RatPoison#64]
The triggerbot shoots like half the time. Most times it doesnt work with the awp properly and I end up just using it as a secondary click where I have to click myself.

**Comment by AStupidRat** [comment]
Inconsistent when? As soon as an enemy comes around a corner? When youre flicking to an enemy? Or just when you're aiming at an enemy it doesn't fire? It uses the torso bones and head bone to determine if it should shoot, depending on the FOV, your crosshair could be on the enemy body but still not shootable.

**Comment by ffauzan** [comment]
Maybe because of the visibility check

**Comment by phooooon** [comment]
@AStupidRat inconsistent on the head when enemy is running across it

**Comment by AStupidRat** [comment]
@phooooon Is this right when they come around a corner and they aren't seen as a target yet? Like @ffauzan said the visibility check could be the issue, since it's a little slow

**Comment by phooooon** [comment]
@AStupidRat no. It doesn't work sometimes when I move my crosshair across their heads

**Comment by Pendramon** [comment]
I assume this happens long distance, probably due to the fov not being a "real fov"

**Comment by AStupidRat** [comment]
@phooooon Latest update references some issues with finding an accurate target, lmk if anything changes

**Comment by phooooon** [comment]
@AStupidRat For the new update. What does fast stop do? 
I dont use the menu bc i play in fullscreen. also a side note if you have time please make a windowed menu as a separate window for those people who use fullscreen mode

**Comment by AStupidRat** [comment]
@phooooon fast stop should slow you down faster, typically when youre moving forward and stop holding W, you slide to a stop, fast stop does that faster, so you can stop moving faster for better accuracy, its a little buggy atm jsyk. And if the game is in fullscreen the menu shouldn't attach to the game and should just be in a black window where you can hit F1 to open the menu there.

**Comment by phooooon** [comment]
@AStupidRat I don't get the menu until the game is closed for some reason.

**Comment by AStupidRat** [comment]
@phooooon Latest update allows you to draw the overlay on any application, check MENU_APP in General.kts, remember most of the scripts only work if the menu isn't active, so make sure you close the menu after opening it regardless

**Comment by phooooon** [comment]
@AStupidRat ty

**Comment by AStupidRat** [comment]
@phooooon The menu items (bomb timer/spectator list) also stay open at all times when not drawing the overlay on csgo, so if you have multiple monitors you can view them on the other monitor as well.
