### ISSUE TITLE
Radar and aim target

### ISSUE THREAD

**Issue by furioushell98** [AStupidRat/RatPoison#66]
Hello. In the beginning of the round Sometimes Radar doesn't update. I mean that i find Bomb holder icon / some enemies' icons from the previous round stuck in wrong places, until i go near the enemies so that bugged one disappears and i get the real one ( i even saw a fake body on that spot and i kept shooting at it for a while lol(happened twice only but the radar thing happened many times)) this happened only on 1.3.2.2, never happened on 1.3.2  btw
I set the aim target to chest for snipers, the problem is that when i'm holding an angle and i spot a leg/ arm/ head the aimbot will still target the chest and will fail or hit a reduced wall shot. Could you maybe add a "nearest" option to hit the nearest target?

**Comment by AStupidRat** [comment]
Latest update should fix some issues with dormant entities. Will look into having aimbot shoot the nearest bone

**Comment by furioushell98** [comment]
Awesome. Thank you for the work, keep it up.

**Comment by AStupidRat** [comment]
@furioushell98 Latest update added a NEAREST aimbone option
