### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by sonosumi** [AStupidRat/RatPoison#67]
* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Press any key to continue . . .

OTHER ERROR WHEN RUNNING IT IN ADMIN : 
'gradlew' is not recognized as an internal or external command,
operable program or batch file.

I've tried downloading newest Java and pretty much made sure everything was updated.
Also have tried disabling windows defender to see if that would work when using the build.bat

Also, why not include a download link to the compiled version on unknowncheats ? 

Thanks in advance <3

**Comment by sonosumi** [comment]
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
Also along with the other stuff, I get this

**Comment by AStupidRat** [comment]
I would suggest googling the error as it doesn't seem to be an issue with the cheat itself. I don't have releases because I update too often and would be more of a hassle for me than its worth, and I'm not associated with the UC post, it's just a random person posting RP.
