### ISSUE TITLE
Interface not doing well

### ISSUE THREAD

**Issue by firas500** [AStupidRat/RatPoison#68]
when i try to load the cheat it only shows me blackscreen with cheats on but nothing in game only aimbot and RCS working not even trigger working 
i have windows 7

**Comment by firas500** [comment]
http://prntscr.com/o5gdi6 this is how i see the cheat

**Comment by AStupidRat** [comment]
Windows 10 is the only supported os

**Comment by yacinus17** [comment]
> http://prntscr.com/o5gdi6 this is how i see the cheat

how do i get this menu ??
