### ISSUE TITLE
RCS causing aim to jerk

### ISSUE THREAD

**Issue by 12aew12e12** [AStupidRat/RatPoison#69]
Everytime you die or swap to another weapon while using RCS, when you switch back to the weapon you were spraying with it will cause the aim to jerk. Return aim setting does not cause or affect this problem.

Here is an example:
https://files.catbox.moe/4votnr.mp4
My RCS settings:
https://files.catbox.moe/nfgzix.png

**Comment by AStupidRat** [comment]
Latest update addresses and should fix this issue
