### ISSUE TITLE
Esp and force aim not working

### ISSUE THREAD

**Issue by Manny13221** [AStupidRat/RatPoison#7]
Esp and force aim seems to not be working
rcs seems to work and bomb timer

**Comment by AStupidRat** [comment]
Latest update should fix it.

**Comment by pravstf97** [comment]
When will the latest update be available ?

**Comment by 0xAC1D98** [comment]
> 
> 
> When will the latest update be available ?

It's available, just clone the repo and build.

**Comment by Manny13221** [comment]
fixed
