### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by MarkoDavkovski** [AStupidRat/RatPoison#71]
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_212' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
Press any key to continue . . .

**Comment by 12aew12e12** [comment]
The solution is literally in the error message. 
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_212' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

Read the guide provided next time.
Download link> https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by AStupidRat** [comment]
What @12aew12e12 said is correct, if needed set your JAVA_HOME to the jdk's directory as well (this might be an option when installing) if not just google how to set JAVA_HOME
